

const List snacks = [
  {'img': 'assets/images/v1.jfif',
  'title': 'Burgers',
  },
  {'img': 'assets/images/v7.jfif',
  'title': 'Pizzas',
  },
  {'img': 'assets/images/v3.jfif',
  'title': 'Pancakes',
  },
  {'img': 'assets/images/v4.jpg',
  'title': 'Ice Creams',
  },
  {'img':'assets/images/v5.jfif',
  'title': 'Smoothies',
  },
  {'img': 'assets/images/v6.jfif',
  'title': 'French Fries',
  },
  {'img': 'assets/images/v2.jfif',
  'title': 'Hot Dogs',
  },
];
